### ISSUE TITLE
It's return Null!

### ISSUE THREAD

**Issue by saormart** [brianmwadime/phonegap_edge_camera#1]
The cameraSuccess is return Null ! Is there a way to fix it ?
I'm using in this way:

```
function cameraSuccess(res){
    var image = document.getElementById('myImage');
    image.src = "data:image/jpeg;base64," + res;
    alert('cameraSuccess: ' + res);
}

function cameraError(res){
    alert('cameraError: ' + res);
}

var cameraOptions = {};
EdgeCamera.takePicture(cameraSuccess, cameraError, cameraOptions);
```

**Comment by brianmwadime** [comment]
@saormart Did you find a way  around this?
Apologies for the late reply I've been inadvertently  neglecting this project for quite awhile.

**Comment by oskarszoon** [comment]
Ran into the same issue getting null values back, @brianmwadime any chance you could have a look at the objective c code?

**Comment by brianmwadime** [comment]
@oskarszoon since it has recurred I'll take a look at it. I'll keep you posted.

**Comment by soskarsson** [comment]
@brianmwadime Any chance you will take a look at this problem? I'm running into it as well.

**Comment by soskarsson** [comment]
Fixed the issue in local fork. see: https://github.com/brianmwadime/phonegap_edge_camera/pull/2

**Comment by brianmwadime** [comment]
@soskarsson thanks! @oskarszoon merging @soskarsson code in the next few.

**Comment by brianmwadime** [comment]
@saormart a fix for this has been merged, confirm it solves this issue.

**Comment by brianmwadime** [comment]
@saormart  @soskarsson @oskarszoon closing this.
